### ISSUE TITLE
Conform to P4Runtime spec

### ISSUE THREAD

**Issue by lkpdn** [P4ELTE/t4p4s#11]
If this issue is okay, I will link PRs to this issue. Otherwise, please close it.

**Comment by slaki** [comment]
Hi,
We have a starter code for the P4Runtime API support. It is far from being complete, but can be used as a satrting point: https://github.com/P4ELTE/P4RuntimeAPI
Best,
Sandor

**Comment by lkpdn** [comment]
Got it, thanks for guiding!

**Comment by lkpdn** [comment]
Turns out that I cannot spare the time to tackle this at least in the next few months so please let me close it. Sorry to bother you.
