### ISSUE TITLE
T4P4S switch exited with error code 139

### ISSUE THREAD

**Issue by irevoire** [P4ELTE/t4p4s#14]
Hello,

I'm trying to run some code directly on my machine.

Before running anything with t4p4s I tried to configure DPDK.
Right now I can run the files in the DPDK/examples directory without any problem so I expect the t4p4s examples to works but I have an error:
```
 ~/t4p4s % ./t4p4s.sh :l2fwd                                                                                                                                 (git)-[master] 
[COMPILE  P4-14] ./examples/l2fwd.p4_14 @std
[COMPILE SWITCH]
  LD l2fwd
  INSTALL-APP l2fwd
  INSTALL-MAP l2fwd.map
[RUN CONTROLLER] dpdk_l2fwd_controller (default for l2fwd@std)
[RUN SWITCH] ./build/l2fwd@std/build/l2fwd
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:02:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:03:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:10fb net_ixgbe
P4_FWD: lcore 1 has nothing to do
P4_FWD: entering main loop on lcore 0
P4_FWD:  -- lcoreid=0 portid=0 rxqueueid=0
P4_FWD:  -- lcoreid=0 portid=1 rxqueueid=0


T4P4S switch exited with error code 139 (Segmentation fault)
 - Runtime options were: -c 0x3 -n 4 -- -p 0x3 --config "\"(0,0,0),(1,0,0)\"" 
```

Thanks in advance

**Comment by nissos** [comment]
Hey, 

I know, it is a bit late. Currently, i am evaluating software switches for my university internship. I had the same error code (with almost the same configuration). I am still evaluating and examining t4p4s, but i just want to give you a quick fix, which worked for me:

By using the autodbg option for t4p4s.sh as well as dbg, i found out, that the error lies within this method ( t4p4s/src/hardware_dep/dpdk/data_plane/dpdk_lib.c ),

```
packet* clone_packet(packet* pd, struct rte_mempool* mempool) {
    return rte_pktmbuf_clone(pd, mempool);
}
```
where mempool seems to be 0x00 at some point. 
Fortunatly, this method is only being called by the broadcast function in t4p4s/src/hardware_dep/dpdk/main.c .
If you have a look in the l2fwd.p4_14 programm, this broadcast is in the table

```
table dmac {
    reads {
        ethernet.dstAddr : exact;
    }
    actions {forward; bcast;}
    size : 512;
}
```
So i have just outcommented the bcast action,

> action bcast() {
>     //modify_field(standard_metadata.egress_port, 100);
> }

as in my setup i know all MAC adresses and added them manually to the controller config. By doing so, i was able to prevent the segementation fault (egress port 100 may be the issue, i mean, i only have 2), and my second PC received sent packets with moongen.
Before i could handle this, a bunch of different errors occured to me (seems, that the newest dpdk version is not working, 19.05 brings you to one error in c compilation from the given source files, which is very strange, but can easily be commented out). I don't fully know, which consequences my chances have yet and not all p4 files are working for me, but it is a start. If i find more, i will keep you updated.

**Comment by VPetyaa** [comment]
This bug in the broadcast is already fixed in the current master.
