### ISSUE TITLE
Compilation issue with mark_to_drop()

### ISSUE THREAD

**Issue by nissos** [P4ELTE/t4p4s#15]
Hey,

I have several issues with the default implementation of mark_to_drop() in  "t4p4s/src/hardware_dep/dpdk/data_plane/dpdkx_v1model.c". When installing t4p4s switch with DPDK-19.05 (i experienced more issues with the newest version), the only issue is that `field_standard_metadata_t_drop `
has not been declared. I have tried to run different p4 programs (as those fields seem to be generated by the python script in the hardware_indep part), but it would still not work. So i commented 
`//MODIFY_INT32_INT32_BITS_PACKET(pd, header_instance_standard_metadata, field_standard_metadata_t_drop, 1)`
 out and everything worked fine. 

I worked around that by adding
`pd->dropped = 1;`
(setting the drop flag in the packet descriptor which causes the packet to drop after emitting stage (see the main.c in hardware_dep/dpdk). It seems to have the same result as the previous implementation.

My question now is, did anybody else experience this issue and am i correct or how do i fix it?

By the way, this method seems to be deprecated, since in p4_16 mark_to_drop(standard_metadata) is being used.

**Comment by VPetyaa** [comment]
This issue is already fixed in the current master
