### ISSUE TITLE
HLIR16 not found in the repository

### ISSUE THREAD

**Issue by elia-azar** [P4ELTE/t4p4s#25]
Tried compiling t4p4s but had the following error: 
Traceback (most recent call last):

 ```
 **File "src/compiler.py", line 19, in <module>
    from hlir16.hlir16 import ***
ImportError: No module named hlir16
Error: P4 to C compilation failed (error code: 1)
```

Tried installing hlir16 with pip but it is not supported anymore

Do you guys have the solution? 
Thanks

**Comment by mharris-t** [comment]
Hi, I have the same issue. How were you able to solve the problem?

**Comment by rst0git** [comment]
@mharris-t `hlir16` has been added as git submodule. You can update the submodules with:
```bash
git submodule update --init --recursive
```

**Comment by mharris-t** [comment]
@rst0git Thank you very much. I was also able to solve the issue by copying the files from [hlir16 repo](https://github.com/P4ELTE/hlir16).
