### ISSUE TITLE
Broadcast and drop port are the same

### ISSUE THREAD

**Issue by manuel-simon** [P4ELTE/t4p4s#37]
Hi, 

it seems that the special ports for dropping and broadcasting packets have the same value.

**src/hardware_dep/dpdk/includes/dpdk_nicon.h**
`14:#define T4P4S_BROADCAST_PORT    100`

**src/hardware_dep/dpdk/includes/dpdk_model_v1model.h**
`20:#define EGRESS_DROP_VALUE   100`

Therefore, it is not possible to broadcast a packet in the v1model. What would be a suitable value for the broadcasting port?

**Comment by kitlei-robert** [comment]
Fixed: the two values are different now.
