### ISSUE TITLE
Link broken at HLIR Section in README

### ISSUE THREAD

**Issue by jannemannX** [P4ELTE/t4p4s#49]
The link in [this](https://github.com/P4ELTE/t4p4s#hlir) section is broken.

[https://github.com/P4ELTE/t4p4s/blob/master/src/hlir16/README.md](https://github.com/P4ELTE/t4p4s/blob/master/src/hlir16/README.md)

**Comment by slaki** [comment]
Thanks for the observation! I fixed the broken link.
